spring.mongodb.uri=${SPRING_MONGODB_URI}
logging.level.root=ERROR
logging.level.org.springframework.data.mongodb.core.ReactiveMongoTemplate=ERROR
logging.level.org.springframework.security=ERROR
spring.mongodb.database=aries_prod_db