spring.application.name=aries-api
server.port=8181

spring.webflux.base-path=/api/v1/
#spring.profiles.active=local

spring.mongodb.database=aries_db
#spring.data.mongodb.logging.level=INFO

aws.region=ap-southeast-2

logging.file.name=logs/myapp.log

logging.level.root=INFO
logging.level.org.springframework.data.mongodb.core.ReactiveMongoTemplate=INFO
logging.level.org.springframework.security=INFO
logging.logback.rollingpolicy.clean-history-on-start=true

#aries Post config
post.truncate.maxlength=500

#prometheus
#management.metrics.distribution.percentiles-histogram.http.ser
#management.endpoints.web.exposure.include=*
management.endpoint.prometheus.access=read-only
management.endpoints.web.exposure.include=health,metrics,prometheus
#management.metrics.enable=true
#management.metrics.distribution.percentiles-histogram=true


# RabbitMQ configuration
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_DEFAULT_USER:kocu}
spring.rabbitmq.password=${RABBITMQ_DEFAULT_PASS:kocu}
spring.rabbitmq.virtual-host=/
spring.rabbitmq.connection-timeout=10000ms

# RabbitMQ queue name
rabbitmq.queue.name=test-queue
